name: Run Code Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Detect Changed Files
      id: changed-files
      uses: tj-actions/changed-files@v44

    - name: Determine File Type
      run: |
        echo "Checking which files changed..."
        CHANGED_FILES="${{ steps.changed-files.outputs.all_changed_files }}"
        for FILE in $CHANGED_FILES; do
          case "$FILE" in
            *.c) echo "C file detected"; echo "LANGUAGE=C" >> $GITHUB_ENV ;;
            *.cpp) echo "C++ file detected"; echo "LANGUAGE=CPP" >> $GITHUB_ENV ;;
            *.py) echo "Python file detected"; echo "LANGUAGE=Python" >> $GITHUB_ENV ;;
            *.java) echo "Java file detected"; echo "LANGUAGE=Java" >> $GITHUB_ENV ;;
          esac
        done

    # Install Dependencies for C
    - name: Install C Dependencies
      if: contains(env.LANGUAGE, 'C')
      run: sudo apt-get install -y gcc

    # Install Dependencies for C++
    - name: Install C++ Dependencies
      if: contains(env.LANGUAGE, 'CPP')
      run: sudo apt-get install -y g++

    # Install Dependencies for Python
    - name: Install Python Dependencies
      if: contains(env.LANGUAGE, 'Python')
      run: |
        python3 -m pip install --upgrade pip pytest

    # Install Dependencies for Java
    - name: Install Java Dependencies
      if: contains(env.LANGUAGE, 'Java')
      run: sudo apt-get install -y default-jdk

    # Compile and Run C Tests
    - name: Compile and Run C Tests
      if: contains(env.LANGUAGE, 'C')
      run: |
        gcc -o tests/test tests/test.c solutions/solution.c
        ./tests/test

    # Compile and Run C++ Tests
    - name: Compile and Run C++ Tests
      if: contains(env.LANGUAGE, 'CPP')
      run: |
        g++ -o tests/test tests/test.cpp solutions/solution.cpp
        ./tests/test

    # Run Python Tests (With Formatted Output)
    - name: Run Python Tests (With Print Output)
      if: contains(env.LANGUAGE, 'Python')
      run: |
        echo "Running Python Test Cases..."
        export PYTHONUNBUFFERED=1  # Ensure output appears live
        export PYTHONPATH=$PWD  # Fix ImportError by setting correct module path
        python3 tests/test.py | tee test_results.log

    # Compile and Run Java Tests
    - name: Compile and Run Java Tests
      if: contains(env.LANGUAGE, 'Java')
      run: |
        javac -d . solutions/Solution.java tests/Test.java
        java tests.Test

    # Upload Test Results
    - name: Upload Test Results
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: test_results.log
